version: '3.7'

services:
  # RTPEngine L7 Load Balancer
  rtpel7lb:
    build: ./
    image: fonoster/fonos-rtpel7lb:latest
    ports:
      - ${RTPEL7LB_NG_PORT}:${RTPEL7LB_NG_PORT}/udp
      - ${RTPEL7LB_ADMIN}:${RTPEL7LB_ADMIN}/udp

  # RTPEngine instance N1
  rtpengine_n1:
    image: psanders/rtpengine:latest
    ports:
      - ${RTPE_N1_NG_PORT}:${RTPE_N1_NG_PORT}/udp
      - ${RTPE_N1_PORT_MIN}-${RTPE_N1_PORT_MAX}:${RTPE_N1_PORT_MIN}-${RTPE_N1_PORT_MAX}/udp
    environment:
      BIND_PORT: ${RTPE_N1_NG_PORT}
      PORT_MIN: ${RTPE_N1_PORT_MIN}
      PORT_MAX: ${RTPE_N1_PORT_MAX}

  # RTPEngine instance N2
  rtpengine_n2:
    image: psanders/rtpengine:latest
    ports:
      - ${RTPE_N2_NG_PORT}:${RTPE_N2_NG_PORT}/udp
      - ${RTPE_N2_PORT_MIN}-${RTPE_N2_PORT_MAX}:${RTPE_N2_PORT_MIN}-${RTPE_N2_PORT_MAX}/udp
    environment:
      BIND_PORT: ${RTPE_N2_NG_PORT}
      PORT_MIN: ${RTPE_N2_PORT_MIN}
      PORT_MAX: ${RTPE_N2_PORT_MAX}

